### PR TITLE
snapp/add vscode recommendations

### PR DESCRIPTION
**Pull request by snapp**
This PR adds some VS Code recommendations to the generated Ansible Collection

### CODE REVIEW

**Review by rhjhunt — CHANGES_REQUESTED** [review]
The addition of the `vscode` settings look good, I would suggest that the *galaxy.yml* file to be modified to include *.vscode/* in the build ignore section.

```yaml
build_ignore:
  - .vscode/
 ```

**Review by brandor5 — COMMENTED** [review]
I think Jacob's suggestion makes sense.

**Comment by snapp** [comment]
> The addition of the `vscode` settings look good, I would suggest that the _galaxy.yml_ file to be modified to include _.vscode/_ in the build ignore section.

@rhjhunt , I've added your recommended change and rebased this branch

One issue I noticed, is that this top level project still has `pre-commit` linting failures that we should investigate.

When I made the modification to the `galaxy.yml` the `check-yaml` linter started failing (we need pipelines for this project 🙄).

You can see these failures if you checkout my `snapp/add_vscode_recommendations` branch and run `pre-commit run --all-files`.

cc: @brandor5

**Review by rhjhunt — APPROVED** [review]
Everything looks good.

**Review by brandor5 — APPROVED** [review]
Thanks for the cleanup, looks good. :)

**Pull request merged**
