### PR TITLE
Add support for user selection of license

### PR DESCRIPTION
**Pull request by snapp**
Resolves: #23

### CODE REVIEW

**Comment by rhjhunt** [comment]
The ability to select a license is a handy feature. As mentioned in issue #23, the Ansible Community has strict licensing requirements, but that is if a collection was to be made publically available. They are more in place to protect Red Hat from hosting non-GPL content. Regardless, I believe if a collection is uploaded to Galaxy and has an incorrect license, that is flagged and must be resolved.

Changes look good to me.

**Review by rhjhunt — DISMISSED** [review]
Pulled the code and tested, no issues.

**Comment by brandor5** [comment]
As I mentioned during a call with @snapp yesterday, I don't feel super strongly one way or the other about this one. I do agree with @rhjhunt that it's handy to have, but part of me thinks "Are we enabling laziness by allowing an easy way to just set something." I believe that this is something people should **really** think about.

**Comment by snapp** [comment]
> As I mentioned during a call with @snapp yesterday, I don't feel super strongly one way or the other about this one. I do agree with @rhjhunt that it's handy to have, but part of me thinks "Are we enabling laziness by allowing an easy way to just set something." I believe that this is something people should **really** think about.
> 
> After reading through what I wrote, maybe I do feel strongly about it? 🤷

I fully agree that people should consider what license they want to cover their code with.

At the very least, this PR was forcing some decision to be made rather than just stamping in the `GPL-3.0-or-later` license as it currently does.

My intent was to provide a subset of what GitHub offers in the `Choose a license` pull-down within their `Create a new repository` as seen in this screenshot:

image

**Comment by markknittel** [comment]
Interesting consideration. I initially thought "that makes a lot of sense" but in thinking about what Brandon mentioned with regards to licensing needing more thought I tend to hesitate agreeing with the simple aspect of picking a license. There are many considerations around this, people can use this internally at a company which may add complexity if there is a plan to widely release it or simply for someone pushing to galaxy. I am more of the opinion at this point that it may be better to highlight  that there should be consideration about it and then possibly a text file that we point them to that can give a brief explanation and pointers to the common licenses.

Then again I may be overthinking this.:)

**Review by brandor5 — APPROVED** [review]
:+1:

**Comment by snapp** [comment]
> This also points to a need for more thorough documentation at the template and generated collection level.

Agreed, I think at the very least the template's `CONTRIBUTING.md` file should explain how the template should combine comments in templated content along with the use of `NOTE:` and `TODO:` comments and explain the use of  the recommended `VSCode` [todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) extension to draw attention to configurable files that were templated in place.

While I'm going to proceed with merging the PR, I do appreciate everyone's input and we can certainly revisit this in the future.

**Pull request merged**
